/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestimonialsImport } from './routes/testimonials'
import { Route as SocialaccountImport } from './routes/social_account'
import { Route as ShopDetailsImport } from './routes/shopDetails'
import { Route as ShopImport } from './routes/shop'
import { Route as SalesCustomerInsightsImport } from './routes/sales-customer-insights'
import { Route as ReviewImport } from './routes/review'
import { Route as ReturnImport } from './routes/return'
import { Route as RegisterImport } from './routes/register'
import { Route as QuizresultImport } from './routes/quiz_result'
import { Route as QuizImport } from './routes/quiz'
import { Route as OrdertrackImport } from './routes/order_track'
import { Route as OrderinstructImport } from './routes/order_instruct'
import { Route as OrderhistoryImport } from './routes/order_history'
import { Route as LoginImport } from './routes/login'
import { Route as JournalImport } from './routes/journal'
import { Route as GlossaryImport } from './routes/glossary'
import { Route as FeedbackImport } from './routes/feedback'
import { Route as FaqImport } from './routes/faq'
import { Route as CollectionsImport } from './routes/collections'
import { Route as CheckoutImport } from './routes/checkout'
import { Route as CartImport } from './routes/cart'
import { Route as BrandlistImport } from './routes/brand_list'
import { Route as BlogImport } from './routes/blog'
import { Route as AdminImport } from './routes/admin'
import { Route as AccountmanageImport } from './routes/account_manage'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as StaffIndexImport } from './routes/staff/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'
import { Route as AdminReportsIndexImport } from './routes/admin/reports/index'
import { Route as AdminOrdersIndexImport } from './routes/admin/orders/index'
import { Route as AdminCouponsIndexImport } from './routes/admin/coupons/index'
import { Route as AdminCosmeticsIndexImport } from './routes/admin/cosmetics/index'
import { Route as AdminBlogsIndexImport } from './routes/admin/blogs/index'
import { Route as AdminBatchesIndexImport } from './routes/admin/batches/index'
import { Route as AdminUsersCartsImport } from './routes/admin/users/carts'
import { Route as AdminIssueTicketsCreateImport } from './routes/admin/issue-tickets/create'
import { Route as AdminCouponsCreateImport } from './routes/admin/coupons/create'
import { Route as AdminCosmeticsSkinTypeImport } from './routes/admin/cosmetics/skin-type'
import { Route as AdminCosmeticsCreateImport } from './routes/admin/cosmetics/create'
import { Route as AdminCosmeticsCosmetictypeImport } from './routes/admin/cosmetics/cosmetic_type'
import { Route as AdminCosmeticsBrandlistImport } from './routes/admin/cosmetics/brand_list'
import { Route as AdminBlogsAddImport } from './routes/admin/blogs/add'
import { Route as AdminBatchesCreateImport } from './routes/admin/batches/create'
import { Route as AdminCouponsEditIdImport } from './routes/admin/coupons/edit/$id'
import { Route as AdminCosmeticsCosmeticIdEditImport } from './routes/admin/cosmetics/$cosmeticId/edit'
import { Route as AdminBatchesBatchIdEditImport } from './routes/admin/batches/$batchId/edit'

// Create/Update Routes

const TestimonialsRoute = TestimonialsImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRoute,
} as any)

const SocialaccountRoute = SocialaccountImport.update({
  id: '/social_account',
  path: '/social_account',
  getParentRoute: () => rootRoute,
} as any)

const ShopDetailsRoute = ShopDetailsImport.update({
  id: '/shopDetails',
  path: '/shopDetails',
  getParentRoute: () => rootRoute,
} as any)

const ShopRoute = ShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any)

const SalesCustomerInsightsRoute = SalesCustomerInsightsImport.update({
  id: '/sales-customer-insights',
  path: '/sales-customer-insights',
  getParentRoute: () => rootRoute,
} as any)

const ReviewRoute = ReviewImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRoute,
} as any)

const ReturnRoute = ReturnImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const QuizresultRoute = QuizresultImport.update({
  id: '/quiz_result',
  path: '/quiz_result',
  getParentRoute: () => rootRoute,
} as any)

const QuizRoute = QuizImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRoute,
} as any)

const OrdertrackRoute = OrdertrackImport.update({
  id: '/order_track',
  path: '/order_track',
  getParentRoute: () => rootRoute,
} as any)

const OrderinstructRoute = OrderinstructImport.update({
  id: '/order_instruct',
  path: '/order_instruct',
  getParentRoute: () => rootRoute,
} as any)

const OrderhistoryRoute = OrderhistoryImport.update({
  id: '/order_history',
  path: '/order_history',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const JournalRoute = JournalImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRoute,
} as any)

const GlossaryRoute = GlossaryImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRoute,
} as any)

const FeedbackRoute = FeedbackImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRoute,
} as any)

const FaqRoute = FaqImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsRoute = CollectionsImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRoute = CheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const BrandlistRoute = BrandlistImport.update({
  id: '/brand_list',
  path: '/brand_list',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AccountmanageRoute = AccountmanageImport.update({
  id: '/account_manage',
  path: '/account_manage',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StaffIndexRoute = StaffIndexImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminReportsIndexRoute = AdminReportsIndexImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminOrdersIndexRoute = AdminOrdersIndexImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCouponsIndexRoute = AdminCouponsIndexImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCosmeticsIndexRoute = AdminCosmeticsIndexImport.update({
  id: '/cosmetics/',
  path: '/cosmetics/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBlogsIndexRoute = AdminBlogsIndexImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBatchesIndexRoute = AdminBatchesIndexImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminUsersCartsRoute = AdminUsersCartsImport.update({
  id: '/users/carts',
  path: '/users/carts',
  getParentRoute: () => AdminRoute,
} as any)

const AdminIssueTicketsCreateRoute = AdminIssueTicketsCreateImport.update({
  id: '/issue-tickets/create',
  path: '/issue-tickets/create',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCouponsCreateRoute = AdminCouponsCreateImport.update({
  id: '/coupons/create',
  path: '/coupons/create',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCosmeticsSkinTypeRoute = AdminCosmeticsSkinTypeImport.update({
  id: '/cosmetics/skin-type',
  path: '/cosmetics/skin-type',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCosmeticsCreateRoute = AdminCosmeticsCreateImport.update({
  id: '/cosmetics/create',
  path: '/cosmetics/create',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCosmeticsCosmetictypeRoute = AdminCosmeticsCosmetictypeImport.update(
  {
    id: '/cosmetics/cosmetic_type',
    path: '/cosmetics/cosmetic_type',
    getParentRoute: () => AdminRoute,
  } as any,
)

const AdminCosmeticsBrandlistRoute = AdminCosmeticsBrandlistImport.update({
  id: '/cosmetics/brand_list',
  path: '/cosmetics/brand_list',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBlogsAddRoute = AdminBlogsAddImport.update({
  id: '/blogs/add',
  path: '/blogs/add',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBatchesCreateRoute = AdminBatchesCreateImport.update({
  id: '/batches/create',
  path: '/batches/create',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCouponsEditIdRoute = AdminCouponsEditIdImport.update({
  id: '/coupons/edit/$id',
  path: '/coupons/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCosmeticsCosmeticIdEditRoute =
  AdminCosmeticsCosmeticIdEditImport.update({
    id: '/cosmetics/$cosmeticId/edit',
    path: '/cosmetics/$cosmeticId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

const AdminBatchesBatchIdEditRoute = AdminBatchesBatchIdEditImport.update({
  id: '/batches/$batchId/edit',
  path: '/batches/$batchId/edit',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/account_manage': {
      id: '/account_manage'
      path: '/account_manage'
      fullPath: '/account_manage'
      preLoaderRoute: typeof AccountmanageImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/brand_list': {
      id: '/brand_list'
      path: '/brand_list'
      fullPath: '/brand_list'
      preLoaderRoute: typeof BrandlistImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutImport
      parentRoute: typeof rootRoute
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqImport
      parentRoute: typeof rootRoute
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackImport
      parentRoute: typeof rootRoute
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryImport
      parentRoute: typeof rootRoute
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/order_history': {
      id: '/order_history'
      path: '/order_history'
      fullPath: '/order_history'
      preLoaderRoute: typeof OrderhistoryImport
      parentRoute: typeof rootRoute
    }
    '/order_instruct': {
      id: '/order_instruct'
      path: '/order_instruct'
      fullPath: '/order_instruct'
      preLoaderRoute: typeof OrderinstructImport
      parentRoute: typeof rootRoute
    }
    '/order_track': {
      id: '/order_track'
      path: '/order_track'
      fullPath: '/order_track'
      preLoaderRoute: typeof OrdertrackImport
      parentRoute: typeof rootRoute
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizImport
      parentRoute: typeof rootRoute
    }
    '/quiz_result': {
      id: '/quiz_result'
      path: '/quiz_result'
      fullPath: '/quiz_result'
      preLoaderRoute: typeof QuizresultImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnImport
      parentRoute: typeof rootRoute
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewImport
      parentRoute: typeof rootRoute
    }
    '/sales-customer-insights': {
      id: '/sales-customer-insights'
      path: '/sales-customer-insights'
      fullPath: '/sales-customer-insights'
      preLoaderRoute: typeof SalesCustomerInsightsImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopImport
      parentRoute: typeof rootRoute
    }
    '/shopDetails': {
      id: '/shopDetails'
      path: '/shopDetails'
      fullPath: '/shopDetails'
      preLoaderRoute: typeof ShopDetailsImport
      parentRoute: typeof rootRoute
    }
    '/social_account': {
      id: '/social_account'
      path: '/social_account'
      fullPath: '/social_account'
      preLoaderRoute: typeof SocialaccountImport
      parentRoute: typeof rootRoute
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/batches/create': {
      id: '/admin/batches/create'
      path: '/batches/create'
      fullPath: '/admin/batches/create'
      preLoaderRoute: typeof AdminBatchesCreateImport
      parentRoute: typeof AdminImport
    }
    '/admin/blogs/add': {
      id: '/admin/blogs/add'
      path: '/blogs/add'
      fullPath: '/admin/blogs/add'
      preLoaderRoute: typeof AdminBlogsAddImport
      parentRoute: typeof AdminImport
    }
    '/admin/cosmetics/brand_list': {
      id: '/admin/cosmetics/brand_list'
      path: '/cosmetics/brand_list'
      fullPath: '/admin/cosmetics/brand_list'
      preLoaderRoute: typeof AdminCosmeticsBrandlistImport
      parentRoute: typeof AdminImport
    }
    '/admin/cosmetics/cosmetic_type': {
      id: '/admin/cosmetics/cosmetic_type'
      path: '/cosmetics/cosmetic_type'
      fullPath: '/admin/cosmetics/cosmetic_type'
      preLoaderRoute: typeof AdminCosmeticsCosmetictypeImport
      parentRoute: typeof AdminImport
    }
    '/admin/cosmetics/create': {
      id: '/admin/cosmetics/create'
      path: '/cosmetics/create'
      fullPath: '/admin/cosmetics/create'
      preLoaderRoute: typeof AdminCosmeticsCreateImport
      parentRoute: typeof AdminImport
    }
    '/admin/cosmetics/skin-type': {
      id: '/admin/cosmetics/skin-type'
      path: '/cosmetics/skin-type'
      fullPath: '/admin/cosmetics/skin-type'
      preLoaderRoute: typeof AdminCosmeticsSkinTypeImport
      parentRoute: typeof AdminImport
    }
    '/admin/coupons/create': {
      id: '/admin/coupons/create'
      path: '/coupons/create'
      fullPath: '/admin/coupons/create'
      preLoaderRoute: typeof AdminCouponsCreateImport
      parentRoute: typeof AdminImport
    }
    '/admin/issue-tickets/create': {
      id: '/admin/issue-tickets/create'
      path: '/issue-tickets/create'
      fullPath: '/admin/issue-tickets/create'
      preLoaderRoute: typeof AdminIssueTicketsCreateImport
      parentRoute: typeof AdminImport
    }
    '/admin/users/carts': {
      id: '/admin/users/carts'
      path: '/users/carts'
      fullPath: '/admin/users/carts'
      preLoaderRoute: typeof AdminUsersCartsImport
      parentRoute: typeof AdminImport
    }
    '/admin/batches/': {
      id: '/admin/batches/'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/cosmetics/': {
      id: '/admin/cosmetics/'
      path: '/cosmetics'
      fullPath: '/admin/cosmetics'
      preLoaderRoute: typeof AdminCosmeticsIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/coupons/': {
      id: '/admin/coupons/'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/batches/$batchId/edit': {
      id: '/admin/batches/$batchId/edit'
      path: '/batches/$batchId/edit'
      fullPath: '/admin/batches/$batchId/edit'
      preLoaderRoute: typeof AdminBatchesBatchIdEditImport
      parentRoute: typeof AdminImport
    }
    '/admin/cosmetics/$cosmeticId/edit': {
      id: '/admin/cosmetics/$cosmeticId/edit'
      path: '/cosmetics/$cosmeticId/edit'
      fullPath: '/admin/cosmetics/$cosmeticId/edit'
      preLoaderRoute: typeof AdminCosmeticsCosmeticIdEditImport
      parentRoute: typeof AdminImport
    }
    '/admin/coupons/edit/$id': {
      id: '/admin/coupons/edit/$id'
      path: '/coupons/edit/$id'
      fullPath: '/admin/coupons/edit/$id'
      preLoaderRoute: typeof AdminCouponsEditIdImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBatchesCreateRoute: typeof AdminBatchesCreateRoute
  AdminBlogsAddRoute: typeof AdminBlogsAddRoute
  AdminCosmeticsBrandlistRoute: typeof AdminCosmeticsBrandlistRoute
  AdminCosmeticsCosmetictypeRoute: typeof AdminCosmeticsCosmetictypeRoute
  AdminCosmeticsCreateRoute: typeof AdminCosmeticsCreateRoute
  AdminCosmeticsSkinTypeRoute: typeof AdminCosmeticsSkinTypeRoute
  AdminCouponsCreateRoute: typeof AdminCouponsCreateRoute
  AdminIssueTicketsCreateRoute: typeof AdminIssueTicketsCreateRoute
  AdminUsersCartsRoute: typeof AdminUsersCartsRoute
  AdminBatchesIndexRoute: typeof AdminBatchesIndexRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminCosmeticsIndexRoute: typeof AdminCosmeticsIndexRoute
  AdminCouponsIndexRoute: typeof AdminCouponsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminBatchesBatchIdEditRoute: typeof AdminBatchesBatchIdEditRoute
  AdminCosmeticsCosmeticIdEditRoute: typeof AdminCosmeticsCosmeticIdEditRoute
  AdminCouponsEditIdRoute: typeof AdminCouponsEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBatchesCreateRoute: AdminBatchesCreateRoute,
  AdminBlogsAddRoute: AdminBlogsAddRoute,
  AdminCosmeticsBrandlistRoute: AdminCosmeticsBrandlistRoute,
  AdminCosmeticsCosmetictypeRoute: AdminCosmeticsCosmetictypeRoute,
  AdminCosmeticsCreateRoute: AdminCosmeticsCreateRoute,
  AdminCosmeticsSkinTypeRoute: AdminCosmeticsSkinTypeRoute,
  AdminCouponsCreateRoute: AdminCouponsCreateRoute,
  AdminIssueTicketsCreateRoute: AdminIssueTicketsCreateRoute,
  AdminUsersCartsRoute: AdminUsersCartsRoute,
  AdminBatchesIndexRoute: AdminBatchesIndexRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminCosmeticsIndexRoute: AdminCosmeticsIndexRoute,
  AdminCouponsIndexRoute: AdminCouponsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminBatchesBatchIdEditRoute: AdminBatchesBatchIdEditRoute,
  AdminCosmeticsCosmeticIdEditRoute: AdminCosmeticsCosmeticIdEditRoute,
  AdminCouponsEditIdRoute: AdminCouponsEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account_manage': typeof AccountmanageRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/brand_list': typeof BrandlistRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/glossary': typeof GlossaryRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/order_history': typeof OrderhistoryRoute
  '/order_instruct': typeof OrderinstructRoute
  '/order_track': typeof OrdertrackRoute
  '/quiz': typeof QuizRoute
  '/quiz_result': typeof QuizresultRoute
  '/register': typeof RegisterRoute
  '/return': typeof ReturnRoute
  '/review': typeof ReviewRoute
  '/sales-customer-insights': typeof SalesCustomerInsightsRoute
  '/shop': typeof ShopRoute
  '/shopDetails': typeof ShopDetailsRoute
  '/social_account': typeof SocialaccountRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/batches/create': typeof AdminBatchesCreateRoute
  '/admin/blogs/add': typeof AdminBlogsAddRoute
  '/admin/cosmetics/brand_list': typeof AdminCosmeticsBrandlistRoute
  '/admin/cosmetics/cosmetic_type': typeof AdminCosmeticsCosmetictypeRoute
  '/admin/cosmetics/create': typeof AdminCosmeticsCreateRoute
  '/admin/cosmetics/skin-type': typeof AdminCosmeticsSkinTypeRoute
  '/admin/coupons/create': typeof AdminCouponsCreateRoute
  '/admin/issue-tickets/create': typeof AdminIssueTicketsCreateRoute
  '/admin/users/carts': typeof AdminUsersCartsRoute
  '/admin/batches': typeof AdminBatchesIndexRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/cosmetics': typeof AdminCosmeticsIndexRoute
  '/admin/coupons': typeof AdminCouponsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/batches/$batchId/edit': typeof AdminBatchesBatchIdEditRoute
  '/admin/cosmetics/$cosmeticId/edit': typeof AdminCosmeticsCosmeticIdEditRoute
  '/admin/coupons/edit/$id': typeof AdminCouponsEditIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account_manage': typeof AccountmanageRoute
  '/blog': typeof BlogRoute
  '/brand_list': typeof BrandlistRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/glossary': typeof GlossaryRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/order_history': typeof OrderhistoryRoute
  '/order_instruct': typeof OrderinstructRoute
  '/order_track': typeof OrdertrackRoute
  '/quiz': typeof QuizRoute
  '/quiz_result': typeof QuizresultRoute
  '/register': typeof RegisterRoute
  '/return': typeof ReturnRoute
  '/review': typeof ReviewRoute
  '/sales-customer-insights': typeof SalesCustomerInsightsRoute
  '/shop': typeof ShopRoute
  '/shopDetails': typeof ShopDetailsRoute
  '/social_account': typeof SocialaccountRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/batches/create': typeof AdminBatchesCreateRoute
  '/admin/blogs/add': typeof AdminBlogsAddRoute
  '/admin/cosmetics/brand_list': typeof AdminCosmeticsBrandlistRoute
  '/admin/cosmetics/cosmetic_type': typeof AdminCosmeticsCosmetictypeRoute
  '/admin/cosmetics/create': typeof AdminCosmeticsCreateRoute
  '/admin/cosmetics/skin-type': typeof AdminCosmeticsSkinTypeRoute
  '/admin/coupons/create': typeof AdminCouponsCreateRoute
  '/admin/issue-tickets/create': typeof AdminIssueTicketsCreateRoute
  '/admin/users/carts': typeof AdminUsersCartsRoute
  '/admin/batches': typeof AdminBatchesIndexRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/cosmetics': typeof AdminCosmeticsIndexRoute
  '/admin/coupons': typeof AdminCouponsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/batches/$batchId/edit': typeof AdminBatchesBatchIdEditRoute
  '/admin/cosmetics/$cosmeticId/edit': typeof AdminCosmeticsCosmeticIdEditRoute
  '/admin/coupons/edit/$id': typeof AdminCouponsEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account_manage': typeof AccountmanageRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/brand_list': typeof BrandlistRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/glossary': typeof GlossaryRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/order_history': typeof OrderhistoryRoute
  '/order_instruct': typeof OrderinstructRoute
  '/order_track': typeof OrdertrackRoute
  '/quiz': typeof QuizRoute
  '/quiz_result': typeof QuizresultRoute
  '/register': typeof RegisterRoute
  '/return': typeof ReturnRoute
  '/review': typeof ReviewRoute
  '/sales-customer-insights': typeof SalesCustomerInsightsRoute
  '/shop': typeof ShopRoute
  '/shopDetails': typeof ShopDetailsRoute
  '/social_account': typeof SocialaccountRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/batches/create': typeof AdminBatchesCreateRoute
  '/admin/blogs/add': typeof AdminBlogsAddRoute
  '/admin/cosmetics/brand_list': typeof AdminCosmeticsBrandlistRoute
  '/admin/cosmetics/cosmetic_type': typeof AdminCosmeticsCosmetictypeRoute
  '/admin/cosmetics/create': typeof AdminCosmeticsCreateRoute
  '/admin/cosmetics/skin-type': typeof AdminCosmeticsSkinTypeRoute
  '/admin/coupons/create': typeof AdminCouponsCreateRoute
  '/admin/issue-tickets/create': typeof AdminIssueTicketsCreateRoute
  '/admin/users/carts': typeof AdminUsersCartsRoute
  '/admin/batches/': typeof AdminBatchesIndexRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/cosmetics/': typeof AdminCosmeticsIndexRoute
  '/admin/coupons/': typeof AdminCouponsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/batches/$batchId/edit': typeof AdminBatchesBatchIdEditRoute
  '/admin/cosmetics/$cosmeticId/edit': typeof AdminCosmeticsCosmeticIdEditRoute
  '/admin/coupons/edit/$id': typeof AdminCouponsEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account_manage'
    | '/admin'
    | '/blog'
    | '/brand_list'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/faq'
    | '/feedback'
    | '/glossary'
    | '/journal'
    | '/login'
    | '/order_history'
    | '/order_instruct'
    | '/order_track'
    | '/quiz'
    | '/quiz_result'
    | '/register'
    | '/return'
    | '/review'
    | '/sales-customer-insights'
    | '/shop'
    | '/shopDetails'
    | '/social_account'
    | '/testimonials'
    | '/admin/'
    | '/staff'
    | '/admin/batches/create'
    | '/admin/blogs/add'
    | '/admin/cosmetics/brand_list'
    | '/admin/cosmetics/cosmetic_type'
    | '/admin/cosmetics/create'
    | '/admin/cosmetics/skin-type'
    | '/admin/coupons/create'
    | '/admin/issue-tickets/create'
    | '/admin/users/carts'
    | '/admin/batches'
    | '/admin/blogs'
    | '/admin/cosmetics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/batches/$batchId/edit'
    | '/admin/cosmetics/$cosmeticId/edit'
    | '/admin/coupons/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account_manage'
    | '/blog'
    | '/brand_list'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/faq'
    | '/feedback'
    | '/glossary'
    | '/journal'
    | '/login'
    | '/order_history'
    | '/order_instruct'
    | '/order_track'
    | '/quiz'
    | '/quiz_result'
    | '/register'
    | '/return'
    | '/review'
    | '/sales-customer-insights'
    | '/shop'
    | '/shopDetails'
    | '/social_account'
    | '/testimonials'
    | '/admin'
    | '/staff'
    | '/admin/batches/create'
    | '/admin/blogs/add'
    | '/admin/cosmetics/brand_list'
    | '/admin/cosmetics/cosmetic_type'
    | '/admin/cosmetics/create'
    | '/admin/cosmetics/skin-type'
    | '/admin/coupons/create'
    | '/admin/issue-tickets/create'
    | '/admin/users/carts'
    | '/admin/batches'
    | '/admin/blogs'
    | '/admin/cosmetics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/batches/$batchId/edit'
    | '/admin/cosmetics/$cosmeticId/edit'
    | '/admin/coupons/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account_manage'
    | '/admin'
    | '/blog'
    | '/brand_list'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/faq'
    | '/feedback'
    | '/glossary'
    | '/journal'
    | '/login'
    | '/order_history'
    | '/order_instruct'
    | '/order_track'
    | '/quiz'
    | '/quiz_result'
    | '/register'
    | '/return'
    | '/review'
    | '/sales-customer-insights'
    | '/shop'
    | '/shopDetails'
    | '/social_account'
    | '/testimonials'
    | '/admin/'
    | '/staff/'
    | '/admin/batches/create'
    | '/admin/blogs/add'
    | '/admin/cosmetics/brand_list'
    | '/admin/cosmetics/cosmetic_type'
    | '/admin/cosmetics/create'
    | '/admin/cosmetics/skin-type'
    | '/admin/coupons/create'
    | '/admin/issue-tickets/create'
    | '/admin/users/carts'
    | '/admin/batches/'
    | '/admin/blogs/'
    | '/admin/cosmetics/'
    | '/admin/coupons/'
    | '/admin/orders/'
    | '/admin/reports/'
    | '/admin/users/'
    | '/admin/batches/$batchId/edit'
    | '/admin/cosmetics/$cosmeticId/edit'
    | '/admin/coupons/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountmanageRoute: typeof AccountmanageRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  BrandlistRoute: typeof BrandlistRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  GlossaryRoute: typeof GlossaryRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  OrderhistoryRoute: typeof OrderhistoryRoute
  OrderinstructRoute: typeof OrderinstructRoute
  OrdertrackRoute: typeof OrdertrackRoute
  QuizRoute: typeof QuizRoute
  QuizresultRoute: typeof QuizresultRoute
  RegisterRoute: typeof RegisterRoute
  ReturnRoute: typeof ReturnRoute
  ReviewRoute: typeof ReviewRoute
  SalesCustomerInsightsRoute: typeof SalesCustomerInsightsRoute
  ShopRoute: typeof ShopRoute
  ShopDetailsRoute: typeof ShopDetailsRoute
  SocialaccountRoute: typeof SocialaccountRoute
  TestimonialsRoute: typeof TestimonialsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountmanageRoute: AccountmanageRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  BrandlistRoute: BrandlistRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  GlossaryRoute: GlossaryRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  OrderhistoryRoute: OrderhistoryRoute,
  OrderinstructRoute: OrderinstructRoute,
  OrdertrackRoute: OrdertrackRoute,
  QuizRoute: QuizRoute,
  QuizresultRoute: QuizresultRoute,
  RegisterRoute: RegisterRoute,
  ReturnRoute: ReturnRoute,
  ReviewRoute: ReviewRoute,
  SalesCustomerInsightsRoute: SalesCustomerInsightsRoute,
  ShopRoute: ShopRoute,
  ShopDetailsRoute: ShopDetailsRoute,
  SocialaccountRoute: SocialaccountRoute,
  TestimonialsRoute: TestimonialsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/account_manage",
        "/admin",
        "/blog",
        "/brand_list",
        "/cart",
        "/checkout",
        "/collections",
        "/faq",
        "/feedback",
        "/glossary",
        "/journal",
        "/login",
        "/order_history",
        "/order_instruct",
        "/order_track",
        "/quiz",
        "/quiz_result",
        "/register",
        "/return",
        "/review",
        "/sales-customer-insights",
        "/shop",
        "/shopDetails",
        "/social_account",
        "/testimonials",
        "/staff/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/account_manage": {
      "filePath": "account_manage.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/",
        "/admin/batches/create",
        "/admin/blogs/add",
        "/admin/cosmetics/brand_list",
        "/admin/cosmetics/cosmetic_type",
        "/admin/cosmetics/create",
        "/admin/cosmetics/skin-type",
        "/admin/coupons/create",
        "/admin/issue-tickets/create",
        "/admin/users/carts",
        "/admin/batches/",
        "/admin/blogs/",
        "/admin/cosmetics/",
        "/admin/coupons/",
        "/admin/orders/",
        "/admin/reports/",
        "/admin/users/",
        "/admin/batches/$batchId/edit",
        "/admin/cosmetics/$cosmeticId/edit",
        "/admin/coupons/edit/$id"
      ]
    },
    "/blog": {
      "filePath": "blog.tsx"
    },
    "/brand_list": {
      "filePath": "brand_list.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/checkout": {
      "filePath": "checkout.tsx"
    },
    "/collections": {
      "filePath": "collections.tsx"
    },
    "/faq": {
      "filePath": "faq.tsx"
    },
    "/feedback": {
      "filePath": "feedback.tsx"
    },
    "/glossary": {
      "filePath": "glossary.tsx"
    },
    "/journal": {
      "filePath": "journal.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/order_history": {
      "filePath": "order_history.tsx"
    },
    "/order_instruct": {
      "filePath": "order_instruct.tsx"
    },
    "/order_track": {
      "filePath": "order_track.tsx"
    },
    "/quiz": {
      "filePath": "quiz.tsx"
    },
    "/quiz_result": {
      "filePath": "quiz_result.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/return": {
      "filePath": "return.tsx"
    },
    "/review": {
      "filePath": "review.tsx"
    },
    "/sales-customer-insights": {
      "filePath": "sales-customer-insights.tsx"
    },
    "/shop": {
      "filePath": "shop.tsx"
    },
    "/shopDetails": {
      "filePath": "shopDetails.tsx"
    },
    "/social_account": {
      "filePath": "social_account.tsx"
    },
    "/testimonials": {
      "filePath": "testimonials.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/staff/": {
      "filePath": "staff/index.tsx"
    },
    "/admin/batches/create": {
      "filePath": "admin/batches/create.tsx",
      "parent": "/admin"
    },
    "/admin/blogs/add": {
      "filePath": "admin/blogs/add.tsx",
      "parent": "/admin"
    },
    "/admin/cosmetics/brand_list": {
      "filePath": "admin/cosmetics/brand_list.tsx",
      "parent": "/admin"
    },
    "/admin/cosmetics/cosmetic_type": {
      "filePath": "admin/cosmetics/cosmetic_type.tsx",
      "parent": "/admin"
    },
    "/admin/cosmetics/create": {
      "filePath": "admin/cosmetics/create.tsx",
      "parent": "/admin"
    },
    "/admin/cosmetics/skin-type": {
      "filePath": "admin/cosmetics/skin-type.tsx",
      "parent": "/admin"
    },
    "/admin/coupons/create": {
      "filePath": "admin/coupons/create.tsx",
      "parent": "/admin"
    },
    "/admin/issue-tickets/create": {
      "filePath": "admin/issue-tickets/create.tsx",
      "parent": "/admin"
    },
    "/admin/users/carts": {
      "filePath": "admin/users/carts.tsx",
      "parent": "/admin"
    },
    "/admin/batches/": {
      "filePath": "admin/batches/index.tsx",
      "parent": "/admin"
    },
    "/admin/blogs/": {
      "filePath": "admin/blogs/index.tsx",
      "parent": "/admin"
    },
    "/admin/cosmetics/": {
      "filePath": "admin/cosmetics/index.tsx",
      "parent": "/admin"
    },
    "/admin/coupons/": {
      "filePath": "admin/coupons/index.tsx",
      "parent": "/admin"
    },
    "/admin/orders/": {
      "filePath": "admin/orders/index.tsx",
      "parent": "/admin"
    },
    "/admin/reports/": {
      "filePath": "admin/reports/index.tsx",
      "parent": "/admin"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    },
    "/admin/batches/$batchId/edit": {
      "filePath": "admin/batches/$batchId/edit.tsx",
      "parent": "/admin"
    },
    "/admin/cosmetics/$cosmeticId/edit": {
      "filePath": "admin/cosmetics/$cosmeticId/edit.tsx",
      "parent": "/admin"
    },
    "/admin/coupons/edit/$id": {
      "filePath": "admin/coupons/edit/$id.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
